development:
  dialect: postgres
  datasource: host=localhost dbname=tf-manifest user=postgres password=postgres sslmode=disable
  dir: pkg/db/migrations/postgres
  table: migrations

production:
  dialect: postgres
  datasource: host=${POSTGRES_HOST} port=${POSTGRES_PORT} dbname=${POSTGRES_DBNAME} user=${POSTGRES_USER} password=${POSTGRES_PASS} sslmode=${POSTGRES_SSLMODE}
  dir: pkg/db/migrations/postgres
  table: migrations
