version: '3.7'

volumes:
  data:

services:
  database:
    container_name: gotemplatepostgres
    image: postgres
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    env_file:
      - .env
  api:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    networks:
      - default
    ports:
      - '8080:8080'
    env_file: .env
