// Code generated by sqlc. DO NOT EDIT.

package store

import ()

type Post struct {
	ID     int32  `json:"id"`
	Title  string `json:"title"`
	Body   string `json:"body"`
	UserID int32  `json:"user_id"`
}

type User struct {
	ID        int32  `json:"id"`
	Email     string `json:"email"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}
